// frontend/src/app/components/admin/SpaceEditDialog.tsx
import { useState, useEffect } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { X } from "lucide-react";

interface SpaceEditDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  space?: {
    id: string;
    name: string;
    icon: string;
    description: string;
  } | null;
  onSave: (data: { name: string; icon: string; description: string }) => void;
}

export function SpaceEditDialog({ open, onOpenChange, space, onSave }: SpaceEditDialogProps) {
  const [name, setName] = useState("");
  const [icon, setIcon] = useState("🔖");
  const [description, setDescription] = useState("");

  useEffect(() => {
    if (space) {
      setName(space.name);
      setIcon(space.icon);
      setDescription(space.description);
    } else {
      setName("");
      setIcon("🔖");
      setDescription("");
    }
  }, [space, open]);

  const handleSave = () => {
    if (!name.trim()) {
      alert("请输入空间名称");
      return;
    }
    onSave({ name: name.trim(), icon, description: description.trim() });
    onOpenChange(false);
  };

  return (
    <Dialog.Root open={open} onOpenChange={onOpenChange}>
      <Dialog.Portal>
        <Dialog.Overlay className="fixed inset-0 bg-black/50 z-50" />
        <Dialog.Content className="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-card border border-border rounded-lg shadow-xl max-w-md w-full p-6 z-50" aria-describedby={undefined}>
          <div className="flex items-start justify-between mb-4">
            <Dialog.Title className="text-lg font-medium">
              {space ? "编辑空间" : "新建空间"}
            </Dialog.Title>
            <Dialog.Close asChild>
              <button className="p-1 hover:bg-accent rounded">
                <X className="h-4 w-4" />
              </button>
            </Dialog.Close>
          </div>

          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium mb-2">
                图标 <span className="text-muted-foreground">(Emoji)</span>
              </label>
              <input
                type="text"
                value={icon}
                onChange={(e) => setIcon(e.target.value)}
                placeholder="🔖"
                className="w-20 px-3 py-2 bg-background border border-border rounded-md text-center text-2xl focus:outline-none focus:ring-2 focus:ring-ring"
                maxLength={2}
              />
            </div>

            <div>
              <label className="block text-sm font-medium mb-2">空间名称 *</label>
              <input
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="如：AI、财经、科技"
                className="w-full px-3 py-2 bg-background border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-ring"
                autoFocus
              />
            </div>

            <div>
              <label className="block text-sm font-medium mb-2">描述</label>
              <textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="简要描述这个空间的用途..."
                rows={3}
                className="w-full px-3 py-2 bg-background border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-ring resize-none"
              />
            </div>

            <div className="flex gap-3 pt-2">
              <Dialog.Close asChild>
                <button className="flex-1 px-4 py-2 bg-secondary text-secondary-foreground rounded-md hover:bg-accent">
                  取消
                </button>
              </Dialog.Close>
              <button
                onClick={handleSave}
                className="flex-1 px-4 py-2 bg-primary text-primary-foreground rounded-md hover:opacity-90"
              >
                保存
              </button>
            </div>
          </div>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
}

// frontend/src/components/admin/SpaceEditDialog.vue
<script setup lang="ts">
// 简化版：空间新建/编辑弹窗，待对照原型 SpaceEditDialog.tsx 精修（图标上传 4 视觉态等）
import { ref, watch } from "vue";
import { X } from "lucide-vue-next";

const props = defineProps<{ open: boolean; space: { name: string; icon: string; description: string } | null }>();
const emit = defineEmits<{ close: []; save: [data: { name: string; icon: string; description: string }] }>();

const name = ref("");
const icon = ref("");
const description = ref("");

watch(
  () => props.open,
  (v) => {
    if (v) {
      name.value = props.space?.name ?? "";
      icon.value = props.space?.icon ?? "";
      description.value = props.space?.description ?? "";
    }
  },
);
</script>

<template>
  <Teleport to="body">
    <div v-if="open" class="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div class="absolute inset-0 bg-black/40" @click="emit('close')" />
      <div class="relative bg-card border border-border rounded-lg shadow-xl w-[460px] max-w-full p-6">
        <div class="flex items-center justify-between mb-5">
          <h3 class="font-medium">{{ space ? "编辑空间" : "新建空间" }}</h3>
          <button @click="emit('close')" class="p-1 rounded-md hover:bg-accent text-muted-foreground"><X class="h-4 w-4" /></button>
        </div>
        <div class="space-y-4">
          <div>
            <label class="block text-sm text-muted-foreground mb-1.5">图标（emoji）</label>
            <input v-model="icon" placeholder="🤖" class="w-full px-3 py-2 bg-background border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-ring" />
          </div>
          <div>
            <label class="block text-sm text-muted-foreground mb-1.5">名称</label>
            <input v-model="name" placeholder="空间名称" class="w-full px-3 py-2 bg-background border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-ring" />
          </div>
          <div>
            <label class="block text-sm text-muted-foreground mb-1.5">描述</label>
            <textarea v-model="description" rows="3" placeholder="空间描述" class="w-full px-3 py-2 bg-background border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-ring resize-none" />
          </div>
        </div>
        <div class="flex justify-end gap-2 mt-6">
          <button @click="emit('close')" class="px-4 py-2 bg-secondary text-secondary-foreground rounded-md hover:bg-accent text-sm">取消</button>
          <button @click="emit('save', { name, icon, description })" class="px-4 py-2 bg-primary text-primary-foreground rounded-md hover:opacity-90 text-sm">保存</button>
        </div>
      </div>
    </div>
  </Teleport>
</template>
