// frontend/src/app/components/admin/SpacesManagement.tsx
import { useState, useEffect } from "react";
import { Plus, MoreHorizontal, Edit2, Trash2, ChevronDown, X, ChevronLeft, ChevronRight, ChevronUp } from "lucide-react";
import { cn } from "../../lib/utils";
import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import { DeleteConfirmDialog } from "./DeleteConfirmDialog";
import { AddSourceDrawer } from "./AddSourceDrawer";
import { SpaceEditDialog } from "./SpaceEditDialog";
import { ChannelEditDialog } from "./ChannelEditDialog";
import { Badge } from "../ui/badge";
import { PlacementTooltip } from "../ui/PlacementTooltip";
import {
  listSpaces, createSpace, updateSpace, deleteSpace, reorderSpaces,
  listChannels, createChannel, updateChannel, deleteChannel, reorderChannels,
  listSpaceSources, pauseSource, resumeSource,
  addDisplayPosition, removeDisplayPosition, moveDisplayPosition,
} from "../../lib/api";

function fmtAgo(iso?: string | null): string {
  if (!iso) return "—";
  const diff = (Date.now() - new Date(iso).getTime()) / 1000;
  if (diff < 60) return "刚刚";
  if (diff < 3600) return `${Math.floor(diff / 60)}分钟前`;
  if (diff < 86400) return `${Math.floor(diff / 3600)}小时前`;
  return `${Math.floor(diff / 86400)}天前`;
}
function mapType(t: string): string {
  return t === "x_twitter" ? "X/Twitter" : t === "rss" ? "RSS" : t;
}

// 后端 space → 原型 shape（驼峰）
function mapSpace(s: any) {
  return {
    id: String(s.id),
    name: s.name,
    icon: s.icon ?? "📁",
    description: s.description ?? "",
    channelCount: s.channel_count ?? 0,
    sourceCount: s.source_count ?? 0,
  };
}
// 后端 channel → 原型 shape
function mapChannel(c: any) {
  return { id: String(c.id), name: c.name, sourceCount: c.source_count ?? 0, isAll: false, description: c.description ?? "" };
}
// listSpaceSources 聚合源 → 原型 shape（positions 端口 space_name 为空，用当前空间名兜底）
function mapSpaceSource(s: any, spaceName: string) {
  const positions = Array.isArray(s.display_positions) ? s.display_positions : [];
  return {
    id: String(s.id),
    name: s.display_name ?? "",
    type: mapType(s.type),
    availability: s.availability_status === "normal" ? "normal" : "needs-fix",
    isRunning: !s.paused,
    tags: Array.isArray(s.domain_tags) ? s.domain_tags : [],
    identity: s.source_identity ?? "",
    fetchConfig: `最近抓取: ${fmtAgo(s.last_fetched_at)}  历史新闻: ${s.total_news_count ?? 0}`,
    placements: positions.map((p: any) => ({ space: spaceName, channel: p.channel_name ?? "" })),
    failureCount: s.consecutive_failures ?? 0,
    _positions: positions,
  };
}

export function SpacesManagement() {
  const [spaces, setSpaces] = useState<any[]>([]);
  const [channels, setChannels] = useState<any[]>([{ id: "all", name: "全部", sourceCount: 0, isAll: true }]);
  const [sources, setSources] = useState<any[]>([]);
  const [selectedSpace, setSelectedSpace] = useState("");
  const [selectedChannel, setSelectedChannel] = useState("all");
  const [hoveredSpace, setHoveredSpace] = useState<string | null>(null);
  const [hoveredChannel, setHoveredChannel] = useState<string | null>(null);
  const [spaceEditDialog, setSpaceEditDialog] = useState<{ open: boolean; space: any }>({ open: false, space: null });
  const [channelEditDialog, setChannelEditDialog] = useState<{ open: boolean; channel: any }>({ open: false, channel: null });
  const [deleteDialog, setDeleteDialog] = useState<{ open: boolean; data: any }>({ open: false, data: null });
  const [addSourceDrawer, setAddSourceDrawer] = useState(false);
  const [sourceToDelete, setSourceToDelete] = useState<string | null>(null);

  const currentSpace = spaces.find((s) => s.id === selectedSpace);
  const currentChannel = channels.find((c) => c.id === selectedChannel);
  const isInAllChannel = selectedChannel === "all";

  // 加载空间列表（mount / 增删改后）
  async function loadSpaces() {
    try {
      const sp: any[] = await listSpaces();
      const list = (sp ?? []).map(mapSpace);
      setSpaces(list);
      setSelectedSpace((prev) => (prev && list.some((s) => s.id === prev) ? prev : list[0]?.id ?? ""));
    } catch (e) { console.error(e); }
  }
  // 加载当前空间频道（前端补「全部」）
  async function loadChannels() {
    if (!selectedSpace) return;
    const sp = spaces.find((s) => s.id === selectedSpace);
    try {
      const ch: any[] = await listChannels(selectedSpace);
      setChannels([{ id: "all", name: "全部", sourceCount: sp?.sourceCount ?? 0, isAll: true }, ...(ch ?? []).map(mapChannel)]);
    } catch { setChannels([{ id: "all", name: "全部", sourceCount: 0, isAll: true }]); }
  }
  // 加载当前空间/频道下的信息源
  async function loadSources() {
    if (!selectedSpace) { setSources([]); return; }
    const sp = spaces.find((s) => s.id === selectedSpace);
    try {
      const raw = await listSpaceSources(selectedSpace, selectedChannel === "all" ? null : selectedChannel);
      setSources(raw.map((s) => mapSpaceSource(s, sp?.name ?? "")));
    } catch { setSources([]); }
  }

  useEffect(() => { loadSpaces(); }, []);
  useEffect(() => { setSelectedChannel("all"); loadChannels(); }, [selectedSpace]);
  useEffect(() => { loadSources(); }, [selectedSpace, selectedChannel]);

  // 信息源已按空间/频道从后端加载，直接用
  const filteredSources = sources;

  // 空间排序
  async function moveSpace(idx: number, dir: -1 | 1) {
    const arr = [...spaces];
    const j = idx + dir;
    if (j < 0 || j >= arr.length) return;
    [arr[idx], arr[j]] = [arr[j], arr[idx]];
    try { await reorderSpaces(arr.map((s, i) => ({ id: s.id, sort_order: (i + 1) * 10 }))); await loadSpaces(); } catch (e) { console.error(e); }
  }
  // 频道排序（channels[0] 是前端造的「全部」，不参与）
  async function moveChannel(idx: number, dir: -1 | 1) {
    const arr = [...channels];
    const j = idx + dir;
    if (j < 1 || j >= arr.length) return;
    [arr[idx], arr[j]] = [arr[j], arr[idx]];
    const real = arr.filter((c) => !c.isAll);
    try { await reorderChannels(selectedSpace, real.map((c, i) => ({ id: c.id, sort_order: (i + 1) * 10 }))); await loadChannels(); } catch (e) { console.error(e); }
  }
  // 暂停 / 恢复
  async function toggleSourcePause(source: any) {
    try {
      if (source.isRunning) await pauseSource(source.id); else await resumeSource(source.id);
      await loadSources();
    } catch (e) { console.error(e); }
  }

  const handleSpaceEdit = (space: any | null) => {
    setSpaceEditDialog({ open: true, space });
  };

  const handleSpaceSave = async (data: { name: string; icon: string; description: string }) => {
    try {
      if (spaceEditDialog.space?.id) await updateSpace(spaceEditDialog.space.id, { name: data.name, description: data.description, icon: data.icon });
      else await createSpace({ name: data.name, description: data.description, icon: data.icon });
      await loadSpaces();
    } catch (e) { console.error(e); }
  };

  const handleSpaceDelete = (space: any) => {
    setDeleteDialog({
      open: true,
      data: {
        type: "space",
        id: space.id,
        name: space.name,
        channelCount: space.channelCount,
        placementCount: space.sourceCount,
        newsCount: 0,
      },
    });
  };

  const handleChannelEdit = (channel: any | null) => {
    if (channel?.isAll) return;
    setChannelEditDialog({
      open: true,
      channel: channel ? { id: channel.id, name: channel.name, description: channel.description ?? "" } : null
    });
  };

  const handleChannelSave = async (data: { name: string; description: string }) => {
    try {
      if (channelEditDialog.channel?.id) await updateChannel(selectedSpace, channelEditDialog.channel.id, { name: data.name, description: data.description });
      else await createChannel(selectedSpace, { name: data.name, description: data.description });
      await loadChannels();
      await loadSpaces();
    } catch (e) { console.error(e); }
  };

  const handleChannelDelete = (channel: any) => {
    setDeleteDialog({
      open: true,
      data: {
        type: "channel",
        id: channel.id,
        name: channel.name,
        spaceName: currentSpace?.name,
        placementCount: channel.sourceCount,
        sourceCount: channel.sourceCount,
        newsCount: 0,
        hasConflicts: false,
      },
    });
  };

  const handleSourceRemove = (source: any) => {
    setSourceToDelete(source.id);
    setDeleteDialog({
      open: true,
      data: {
        type: "remove-placement",
        sourceName: source.name,
        location: `${currentSpace?.name} / ${currentChannel?.name}`,
        isLastPlacement: (source._positions?.length ?? 0) <= 1,
      },
    });
  };

  return (
    <div className="flex flex-col h-full">
      {/* Spaces Row */}
      <div className="border-b border-border p-6">
        <div className="flex items-center gap-2 mb-3">
          <h4 className="text-sm font-medium">空间</h4>
          <button className="p-1 hover:bg-accent rounded">
            <MoreHorizontal className="h-4 w-4" />
          </button>
        </div>

        <div className="flex gap-3 flex-wrap">
          {spaces.map((space, idx) => (
            <div
              key={space.id}
              onMouseEnter={() => setHoveredSpace(space.id)}
              onMouseLeave={() => setHoveredSpace(null)}
              className="relative"
            >
              <div
                onClick={() => {
                  setSelectedSpace(space.id);
                  setSelectedChannel("all");
                }}
                onDoubleClick={() => handleSpaceEdit(space)}
                className={cn(
                    "w-[180px] p-3 rounded-lg border-2 transition-all text-left relative cursor-pointer",
                    selectedSpace === space.id
                      ? "border-primary bg-primary/5"
                      : "border-border bg-card hover:border-primary/50"
                  )}
                >
                  <div className="flex items-start gap-2 mb-2">
                    <div className="text-2xl">{space.icon}</div>
                    <div className="flex-1 min-w-0">
                      <div className="font-medium">{space.name}</div>
                    </div>
                    {selectedSpace === space.id && (
                      <div className="flex gap-0.5">
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            handleSpaceEdit(space);
                          }}
                          className="p-0.5 hover:bg-accent rounded"
                        >
                          <Edit2 className="h-3 w-3" />
                        </button>
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            handleSpaceDelete(space);
                          }}
                          className="p-0.5 hover:bg-accent rounded text-destructive"
                        >
                          <X className="h-3 w-3" />
                        </button>
                      </div>
                    )}
                  </div>
                  <div className="text-xs text-muted-foreground">
                    {space.channelCount}个频道 · {space.sourceCount}个信息源
                  </div>

                  {/* Sort arrows */}
                  {hoveredSpace === space.id && (
                    <>
                      {idx > 0 && (
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            moveSpace(idx, -1);
                          }}
                          className="absolute -left-7 top-1/2 -translate-y-1/2 p-0.5 hover:bg-accent rounded"
                        >
                          <ChevronLeft className="h-4 w-4" />
                        </button>
                      )}
                      {idx < spaces.length - 1 && (
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            moveSpace(idx, 1);
                          }}
                          className="absolute -right-7 top-1/2 -translate-y-1/2 p-0.5 hover:bg-accent rounded"
                        >
                          <ChevronRight className="h-4 w-4" />
                        </button>
                      )}
                    </>
                  )}
                </div>
            </div>
          ))}

          <button
            onClick={() => handleSpaceEdit(null)}
            className="w-[180px] p-3 rounded-lg border-2 border-dashed border-border hover:border-primary hover:bg-primary/5 transition-all flex flex-col items-center justify-center gap-1 text-sm text-muted-foreground hover:text-foreground"
          >
            <Plus className="h-5 w-5" />
            <span>新建空间</span>
          </button>
        </div>
      </div>

      {/* Content Area: Channels + Sources */}
      <div className="flex flex-1 overflow-hidden">
        {/* Left: Channels */}
        <div className="w-56 border-r border-border bg-card p-4">
          <div className="flex items-center justify-between mb-3">
            <h4 className="text-sm font-medium">频道</h4>
            <button className="p-1 hover:bg-accent rounded">
              <MoreHorizontal className="h-4 w-4" />
            </button>
          </div>

          <div className="space-y-1">
            {channels.map((channel, idx) => (
              <div
                key={channel.id}
                onMouseEnter={() => setHoveredChannel(channel.id)}
                onMouseLeave={() => setHoveredChannel(null)}
                className="relative"
              >
                <button
                  onClick={() => setSelectedChannel(channel.id)}
                  onDoubleClick={() => handleChannelEdit(channel)}
                  className={cn(
                    "w-full px-3 py-2 rounded-md transition-colors text-left text-sm",
                    selectedChannel === channel.id
                      ? "bg-secondary text-secondary-foreground font-medium"
                      : "hover:bg-accent"
                  )}
                >
                  <div className="flex items-center justify-between">
                    <span>{channel.name}</span>
                    <div className="flex items-center gap-2">
                      {!channel.isAll && (
                        <span className="text-xs text-muted-foreground">{channel.sourceCount}</span>
                      )}
                      {selectedChannel === channel.id && !channel.isAll && (
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            handleChannelDelete(channel);
                          }}
                          className="p-0.5 hover:bg-accent rounded text-destructive"
                        >
                          <Trash2 className="h-3 w-3" />
                        </button>
                      )}
                    </div>
                  </div>
                </button>

                {/* Sort arrows for non-all channels */}
                {!channel.isAll && hoveredChannel === channel.id && (
                  <div className="absolute -right-6 top-1/2 -translate-y-1/2 flex flex-col gap-0.5">
                    {idx > 1 && (
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          moveChannel(idx, -1);
                        }}
                        className="p-0.5 hover:bg-accent rounded"
                      >
                        <ChevronUp className="h-3 w-3" />
                      </button>
                    )}
                    {idx < channels.length - 1 && (
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          moveChannel(idx, 1);
                        }}
                        className="p-0.5 hover:bg-accent rounded"
                      >
                        <ChevronDown className="h-3 w-3" />
                      </button>
                    )}
                  </div>
                )}
              </div>
            ))}

            <button
              onClick={() => handleChannelEdit(null)}
              className="w-full px-3 py-2 rounded-md hover:bg-accent text-left text-sm text-primary"
            >
              <Plus className="h-3 w-3 inline mr-2" />
              新建频道
            </button>
          </div>
        </div>

        {/* Right: Sources */}
        <div className="flex-1 overflow-auto">
          <div className="p-6">
            {/* Header */}
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-2 text-sm">
                <span className="text-muted-foreground">当前:</span>
                <span className="text-primary">{currentSpace?.name}</span>
                <span className="text-muted-foreground">·</span>
                <span className="text-primary">{currentChannel?.name}</span>
                <span className="text-muted-foreground">
                  {filteredSources.length}个信息源
                </span>
              </div>
              <button
                onClick={() => setAddSourceDrawer(true)}
                className="px-4 py-2 bg-primary text-primary-foreground rounded-md hover:opacity-90 flex items-center gap-2"
              >
                <Plus className="h-4 w-4" />
                添加信息源
              </button>
            </div>

            {/* Sources List */}
            {filteredSources.length === 0 ? (
              <div className="text-center py-12">
                <p className="text-muted-foreground">当前频道暂无信息源</p>
                <button
                  onClick={() => setAddSourceDrawer(true)}
                  className="mt-4 px-4 py-2 bg-secondary text-secondary-foreground rounded-md hover:bg-accent"
                >
                  <Plus className="h-4 w-4 inline mr-2" />
                  添加第一个信息源
                </button>
              </div>
            ) : (
              <div className="space-y-3">
                {filteredSources.map((source) => (
                  <div key={source.id} className="bg-card border border-border rounded-lg p-4">
                    {/* Source Header */}
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <div className="flex items-center gap-2 mb-2">
                          <h4 className="font-medium">{source.name}</h4>
                          <span className="px-2 py-0.5 bg-blue-100 text-blue-800 text-xs rounded">
                            {source.type}
                          </span>
                          <span className={cn(
                            "px-2 py-0.5 text-xs rounded",
                            source.availability === "normal" && "bg-green-100 text-green-800",
                            source.availability === "needs-fix" && "bg-orange-100 text-orange-800"
                          )}>
                            {source.availability === "normal" ? "正常" : "待修复"}
                          </span>
                          <span className="px-2 py-0.5 bg-green-100 text-green-800 text-xs rounded flex items-center gap-1">
                            <div className={cn(
                              "h-1.5 w-1.5 rounded-full",
                              source.isRunning ? "bg-green-600" : "bg-gray-400"
                            )} />
                            {source.isRunning ? "抓取中" : "已停止"}
                          </span>
                        </div>

                        <div className="flex items-center gap-2 mb-2 flex-wrap text-sm">
                          {source.tags.map((tag) => (
                            <span key={tag} className="px-2 py-0.5 bg-secondary text-secondary-foreground text-xs rounded">
                              {tag}
                            </span>
                          ))}
                          <span className="text-muted-foreground">
                            身份: {source.identity}
                          </span>
                          <span className="text-muted-foreground">
                            {source.fetchConfig}
                          </span>
                        </div>

                        {/* Placements info - only show in "All" view */}
                        {isInAllChannel && (
                          <PlacementTooltip placements={source.placements}>
                            <span className="text-sm text-muted-foreground hover:text-foreground inline-flex items-center gap-1 cursor-pointer">
                              使用于 {source.placements.length} 个位置
                            </span>
                          </PlacementTooltip>
                        )}
                      </div>

                      {/* Action Buttons */}
                      <div className="flex items-center gap-2 ml-4">
                        <button className="px-3 py-1.5 bg-secondary text-secondary-foreground rounded hover:bg-accent text-sm">
                          详情
                        </button>
                        <button
                          onClick={() => toggleSourcePause(source)}
                          className="px-3 py-1.5 bg-secondary text-secondary-foreground rounded hover:bg-accent text-sm"
                        >
                          暂停
                        </button>

                        {/* Channel display/selector */}
                        {isInAllChannel ? (
                          <DropdownMenu.Root>
                            <DropdownMenu.Trigger asChild>
                              <button className="px-3 py-1.5 bg-secondary text-secondary-foreground rounded hover:bg-accent text-sm flex items-center gap-1">
                                {source.placements.find(p => p.space === currentSpace?.name)?.channel || "未分配"}
                                <ChevronDown className="h-3 w-3" />
                              </button>
                            </DropdownMenu.Trigger>
                            <DropdownMenu.Portal>
                              <DropdownMenu.Content className="min-w-[160px] bg-popover border border-border rounded-md shadow-lg p-1 z-50">
                                <DropdownMenu.RadioGroup
                                  value={source.placements.find(p => p.space === currentSpace?.name)?.channel || ""}
                                  onValueChange={async (value) => {
                                    try {
                                      const pos = source._positions?.[0];
                                      const ch = channels.find((c) => c.name === value && !c.isAll);
                                      if (pos && ch) { await moveDisplayPosition(pos.id, ch.id); await loadSources(); await loadChannels(); }
                                    } catch (e) { console.error(e); }
                                  }}
                                >
                                  {channels
                                    .filter(c => !c.isAll)
                                    .map((channel) => (
                                      <DropdownMenu.RadioItem
                                        key={channel.id}
                                        value={channel.name}
                                        className="px-3 py-2 text-sm rounded hover:bg-accent cursor-pointer outline-none flex items-center gap-2"
                                      >
                                        <DropdownMenu.ItemIndicator className="w-4">
                                          ●
                                        </DropdownMenu.ItemIndicator>
                                        {channel.name}
                                      </DropdownMenu.RadioItem>
                                    ))}
                                </DropdownMenu.RadioGroup>
                              </DropdownMenu.Content>
                            </DropdownMenu.Portal>
                          </DropdownMenu.Root>
                        ) : (
                          <span className="px-3 py-1.5 bg-muted text-muted-foreground rounded text-sm">
                            当前频道: {currentChannel?.name}
                          </span>
                        )}

                        <button
                          onClick={() => handleSourceRemove(source)}
                          className="px-3 py-1.5 bg-destructive/10 text-destructive rounded hover:bg-destructive/20 text-sm"
                        >
                          从此位置移除
                        </button>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Space Edit Dialog */}
      <SpaceEditDialog
        open={spaceEditDialog.open}
        onOpenChange={(open) => setSpaceEditDialog({ ...spaceEditDialog, open })}
        space={spaceEditDialog.space}
        onSave={handleSpaceSave}
      />

      {/* Channel Edit Dialog */}
      <ChannelEditDialog
        open={channelEditDialog.open}
        onOpenChange={(open) => setChannelEditDialog({ ...channelEditDialog, open })}
        channel={channelEditDialog.channel}
        onSave={handleChannelSave}
      />

      {/* Delete Confirmation Dialog */}
      <DeleteConfirmDialog
        open={deleteDialog.open}
        onOpenChange={(open) => setDeleteDialog({ ...deleteDialog, open })}
        data={deleteDialog.data}
        onConfirm={async () => {
          const d = deleteDialog.data;
          try {
            if (d?.type === "space") await deleteSpace(d.id);
            else if (d?.type === "channel") await deleteChannel(selectedSpace, d.id);
            else if (d?.type === "remove-placement") {
              const src = sources.find((s) => s.id === sourceToDelete);
              const positions = isInAllChannel
                ? (src?._positions ?? [])
                : (src?._positions ?? []).filter((p: any) => String(p.channel_id) === selectedChannel);
              for (const p of positions) await removeDisplayPosition(p.id);
            }
            await loadSpaces();
            await loadChannels();
            await loadSources();
          } catch (e) { console.error(e); }
          setDeleteDialog({ open: false, data: null });
          setSourceToDelete(null);
        }}
      />

      {/* Add Source Drawer */}
      <AddSourceDrawer
        open={addSourceDrawer}
        onClose={() => setAddSourceDrawer(false)}
        spaceName={currentSpace?.name || ""}
        channelName={currentChannel?.name || ""}
        onAddSource={async (sourceId) => {
          try {
            await addDisplayPosition({ source_id: sourceId, space_id: selectedSpace, channel_id: isInAllChannel ? null : selectedChannel });
            await loadSources();
            await loadChannels();
            await loadSpaces();
          } catch (e) { console.error(e); }
        }}
      />
    </div>
  );
}

// frontend/src/components/admin/SpacesManagement.vue
<script setup lang="ts">
import { ref, computed, onMounted } from "vue";
import { Plus, MoreHorizontal, Edit2, Trash2, ChevronDown, X, ChevronLeft, ChevronRight, ChevronUp } from "lucide-vue-next";
import { cn } from "@/lib/utils";
import DeleteConfirmDialog from "./DeleteConfirmDialog.vue";
import AddSourceDrawer from "./AddSourceDrawer.vue";
import SpaceEditDialog from "./SpaceEditDialog.vue";
import ChannelEditDialog from "./ChannelEditDialog.vue";
import PlacementTooltip from "@/components/ui/PlacementTooltip.vue";
import { listSpaces, listChannels, listSpaceSources, pauseSource, resumeSource, deleteSpace, deleteChannel, createSpace, updateSpace, createChannel, updateChannel } from "@/lib/api";

const typeLabels: Record<string, string> = { x_twitter: "X/Twitter", rss: "RSS" };
function fmtAgo(iso?: string): string {
  if (!iso) return "从未";
  const diff = (Date.now() - new Date(iso).getTime()) / 1000;
  if (diff < 3600) return `${Math.max(1, Math.floor(diff / 60))}分钟前`;
  if (diff < 86400) return `${Math.floor(diff / 3600)}小时前`;
  return `${Math.floor(diff / 86400)}天前`;
}

const spaces = ref<any[]>([]);
const channels = ref<any[]>([{ id: "all", name: "全部", sourceCount: 0, isAll: true }]);
const sources = ref<any[]>([]);
const selectedSpace = ref("");
const selectedChannel = ref("all");
const hoveredSpace = ref<string | null>(null);
const hoveredChannel = ref<string | null>(null);
const spaceEditDialog = ref<{ open: boolean; space: any }>({ open: false, space: null });
const channelEditDialog = ref<{ open: boolean; channel: any }>({ open: false, channel: null });
const deleteDialog = ref<{ open: boolean; data: any }>({ open: false, data: null });
const addSourceDrawer = ref(false);

const currentSpace = computed(() => spaces.value.find((s) => s.id === selectedSpace.value));
const currentChannel = computed(() => channels.value.find((c) => c.id === selectedChannel.value));
const isInAllChannel = computed(() => selectedChannel.value === "all");
const filteredSources = computed(() => sources.value);

function mapSpace(s: any) {
  return { id: s.id, name: s.name, icon: s.icon || "📁", description: s.description || "", channelCount: s.channel_count ?? 0, sourceCount: s.source_count ?? 0 };
}
function mapSource(s: any) {
  return {
    id: s.id, name: s.display_name ?? s.source_identity ?? "未命名", type: typeLabels[s.type] ?? s.type,
    availability: s.availability_status ?? "normal", isRunning: !s.paused,
    tags: Array.isArray(s.domain_tags) ? s.domain_tags : [], identity: s.source_identity ?? "",
    fetchConfig: `最近抓取: ${fmtAgo(s.last_fetched_at)}  历史新闻: ${s.total_news_count ?? 0}`,
    placements: (s.display_positions ?? []).map((p: any) => ({ space: p.space_name, channel: p.channel_name })),
  };
}

async function loadSpaces() {
  try {
    const r: any = await listSpaces();
    spaces.value = (r ?? []).map(mapSpace);
    if (!selectedSpace.value && spaces.value.length) await selectSpace(spaces.value[0].id);
  } catch { spaces.value = []; }
}
async function loadChannels() {
  try {
    const r: any = await listChannels(selectedSpace.value);
    channels.value = [
      { id: "all", name: "全部", sourceCount: currentSpace.value?.sourceCount ?? 0, isAll: true },
      ...(r ?? []).map((c: any) => ({ id: c.id, name: c.name, sourceCount: c.source_count ?? 0, isAll: false })),
    ];
  } catch { channels.value = [{ id: "all", name: "全部", sourceCount: 0, isAll: true }]; }
}
async function loadSources() {
  try {
    const r: any = await listSpaceSources(selectedSpace.value, selectedChannel.value === "all" ? null : selectedChannel.value);
    sources.value = (r ?? []).map(mapSource);
  } catch { sources.value = []; }
}

async function selectSpace(id: string) {
  selectedSpace.value = id;
  selectedChannel.value = "all";
  await Promise.all([loadChannels(), loadSources()]);
}
async function selectChannel(id: string) {
  selectedChannel.value = id;
  await loadSources();
}
function handleSpaceEdit(space: any) { spaceEditDialog.value = { open: true, space }; }
function handleSpaceDelete(space: any) { deleteDialog.value = { open: true, data: { type: "space", id: space.id, name: space.name, channelCount: space.channelCount, placementCount: space.sourceCount, newsCount: 0 } }; }
function handleChannelEdit(channel: any) { if (channel?.isAll) return; channelEditDialog.value = { open: true, channel: channel ? { id: channel.id, name: channel.name, description: "" } : null }; }
function handleChannelDelete(channel: any) { deleteDialog.value = { open: true, data: { type: "channel", id: channel.id, name: channel.name, spaceName: currentSpace.value?.name, placementCount: channel.sourceCount, sourceCount: channel.sourceCount, newsCount: 0 } }; }
function handleSourceRemove(source: any) { deleteDialog.value = { open: true, data: { type: "remove-placement", sourceName: source.name, location: `${currentSpace.value?.name} / ${currentChannel.value?.name}` } }; }
function currentChannelOf(source: any) { return source.placements.find((p: any) => p.space === currentSpace.value?.name)?.channel || "未分配"; }

async function toggleSourcePause(source: any) {
  try { source.isRunning ? await pauseSource(source.id) : await resumeSource(source.id); await loadSources(); } catch { /* ignore */ }
}
async function handleSpaceSave(data: any) {
  try {
    if (spaceEditDialog.value.space?.id) await updateSpace(spaceEditDialog.value.space.id, data);
    else await createSpace(data);
    await loadSpaces();
  } catch { /* ignore */ }
  spaceEditDialog.value = { open: false, space: null };
}
async function handleChannelSave(data: any) {
  try {
    if (channelEditDialog.value.channel?.id) await updateChannel(selectedSpace.value, channelEditDialog.value.channel.id, data);
    else await createChannel(selectedSpace.value, data);
    await loadChannels();
  } catch { /* ignore */ }
  channelEditDialog.value = { open: false, channel: null };
}
async function handleDeleteConfirm() {
  const d = deleteDialog.value.data;
  try {
    if (d?.type === "space") { await deleteSpace(d.id); await loadSpaces(); }
    else if (d?.type === "channel") { await deleteChannel(selectedSpace.value, d.id); await loadChannels(); await loadSources(); }
  } catch { /* ignore */ }
  deleteDialog.value = { open: false, data: null };
}

onMounted(loadSpaces);
</script>

<template>
  <div class="flex flex-col h-full">
    <!-- Spaces Row -->
    <div class="border-b border-border p-6">
      <div class="flex items-center gap-2 mb-3">
        <h4 class="text-sm font-medium">空间</h4>
        <button class="p-1 hover:bg-accent rounded"><MoreHorizontal class="h-4 w-4" /></button>
      </div>
      <div class="flex gap-3 flex-wrap">
        <div v-for="(space, idx) in spaces" :key="space.id" @mouseenter="hoveredSpace = space.id" @mouseleave="hoveredSpace = null" class="relative">
          <div
            @click="selectSpace(space.id)"
            @dblclick="handleSpaceEdit(space)"
            :class="cn('w-[180px] p-3 rounded-lg border-2 transition-all text-left relative cursor-pointer', selectedSpace === space.id ? 'border-primary bg-primary/5' : 'border-border bg-card hover:border-primary/50')"
          >
            <div class="flex items-start gap-2 mb-2">
              <div class="text-2xl">{{ space.icon }}</div>
              <div class="flex-1 min-w-0"><div class="font-medium">{{ space.name }}</div></div>
              <div v-if="selectedSpace === space.id" class="flex gap-0.5">
                <button @click.stop="handleSpaceEdit(space)" class="p-0.5 hover:bg-accent rounded"><Edit2 class="h-3 w-3" /></button>
                <button @click.stop="handleSpaceDelete(space)" class="p-0.5 hover:bg-accent rounded text-destructive"><X class="h-3 w-3" /></button>
              </div>
            </div>
            <div class="text-xs text-muted-foreground">{{ space.channelCount }}个频道 · {{ space.sourceCount }}个信息源</div>
            <template v-if="hoveredSpace === space.id">
              <button v-if="idx > 0" @click.stop class="absolute -left-7 top-1/2 -translate-y-1/2 p-0.5 hover:bg-accent rounded"><ChevronLeft class="h-4 w-4" /></button>
              <button v-if="idx < spaces.length - 1" @click.stop class="absolute -right-7 top-1/2 -translate-y-1/2 p-0.5 hover:bg-accent rounded"><ChevronRight class="h-4 w-4" /></button>
            </template>
          </div>
        </div>
        <button @click="handleSpaceEdit(null)" class="w-[180px] p-3 rounded-lg border-2 border-dashed border-border hover:border-primary hover:bg-primary/5 transition-all flex flex-col items-center justify-center gap-1 text-sm text-muted-foreground hover:text-foreground">
          <Plus class="h-5 w-5" /><span>新建空间</span>
        </button>
      </div>
    </div>

    <!-- Content: Channels + Sources -->
    <div class="flex flex-1 overflow-hidden">
      <div class="w-56 border-r border-border bg-card p-4">
        <div class="flex items-center justify-between mb-3">
          <h4 class="text-sm font-medium">频道</h4>
          <button class="p-1 hover:bg-accent rounded"><MoreHorizontal class="h-4 w-4" /></button>
        </div>
        <div class="space-y-1">
          <div v-for="(channel, idx) in channels" :key="channel.id" @mouseenter="hoveredChannel = channel.id" @mouseleave="hoveredChannel = null" class="relative">
            <button
              @click="selectChannel(channel.id)"
              @dblclick="handleChannelEdit(channel)"
              :class="cn('w-full px-3 py-2 rounded-md transition-colors text-left text-sm', selectedChannel === channel.id ? 'bg-secondary text-secondary-foreground font-medium' : 'hover:bg-accent')"
            >
              <div class="flex items-center justify-between">
                <span>{{ channel.name }}</span>
                <div class="flex items-center gap-2">
                  <span v-if="!channel.isAll" class="text-xs text-muted-foreground">{{ channel.sourceCount }}</span>
                  <button v-if="selectedChannel === channel.id && !channel.isAll" @click.stop="handleChannelDelete(channel)" class="p-0.5 hover:bg-accent rounded text-destructive"><Trash2 class="h-3 w-3" /></button>
                </div>
              </div>
            </button>
            <div v-if="!channel.isAll && hoveredChannel === channel.id" class="absolute -right-6 top-1/2 -translate-y-1/2 flex flex-col gap-0.5">
              <button v-if="idx > 1" @click.stop class="p-0.5 hover:bg-accent rounded"><ChevronUp class="h-3 w-3" /></button>
              <button v-if="idx < channels.length - 1" @click.stop class="p-0.5 hover:bg-accent rounded"><ChevronDown class="h-3 w-3" /></button>
            </div>
          </div>
          <button @click="handleChannelEdit(null)" class="w-full px-3 py-2 rounded-md hover:bg-accent text-left text-sm text-primary"><Plus class="h-3 w-3 inline mr-2" />新建频道</button>
        </div>
      </div>

      <div class="flex-1 overflow-auto">
        <div class="p-6">
          <div class="flex items-center justify-between mb-6">
            <div class="flex items-center gap-2 text-sm">
              <span class="text-muted-foreground">当前:</span>
              <span class="text-primary">{{ currentSpace?.name }}</span>
              <span class="text-muted-foreground">·</span>
              <span class="text-primary">{{ currentChannel?.name }}</span>
              <span class="text-muted-foreground">{{ filteredSources.length }}个信息源</span>
            </div>
            <button @click="addSourceDrawer = true" class="px-4 py-2 bg-primary text-primary-foreground rounded-md hover:opacity-90 flex items-center gap-2"><Plus class="h-4 w-4" />添加信息源</button>
          </div>

          <div v-if="filteredSources.length === 0" class="text-center py-12">
            <p class="text-muted-foreground">当前频道暂无信息源</p>
            <button @click="addSourceDrawer = true" class="mt-4 px-4 py-2 bg-secondary text-secondary-foreground rounded-md hover:bg-accent"><Plus class="h-4 w-4 inline mr-2" />添加第一个信息源</button>
          </div>
          <div v-else class="space-y-3">
            <div v-for="source in filteredSources" :key="source.id" class="bg-card border border-border rounded-lg p-4">
              <div class="flex items-start justify-between">
                <div class="flex-1">
                  <div class="flex items-center gap-2 mb-2">
                    <h4 class="font-medium">{{ source.name }}</h4>
                    <span class="px-2 py-0.5 bg-blue-100 text-blue-800 text-xs rounded">{{ source.type }}</span>
                    <span :class="cn('px-2 py-0.5 text-xs rounded', source.availability === 'normal' ? 'bg-green-100 text-green-800' : 'bg-orange-100 text-orange-800')">{{ source.availability === "normal" ? "正常" : "待修复" }}</span>
                    <span class="px-2 py-0.5 bg-green-100 text-green-800 text-xs rounded flex items-center gap-1"><span :class="cn('h-1.5 w-1.5 rounded-full', source.isRunning ? 'bg-green-600' : 'bg-gray-400')" />{{ source.isRunning ? "抓取中" : "已停止" }}</span>
                  </div>
                  <div class="flex items-center gap-2 mb-2 flex-wrap text-sm">
                    <span v-for="tag in source.tags" :key="tag" class="px-2 py-0.5 bg-secondary text-secondary-foreground text-xs rounded">{{ tag }}</span>
                    <span class="text-muted-foreground">身份: {{ source.identity }}</span>
                    <span class="text-muted-foreground">{{ source.fetchConfig }}</span>
                  </div>
                  <PlacementTooltip v-if="isInAllChannel" :placements="source.placements">
                    <span class="text-sm text-muted-foreground hover:text-foreground inline-flex items-center gap-1 cursor-pointer">使用于 {{ source.placements.length }} 个位置</span>
                  </PlacementTooltip>
                </div>
                <div class="flex items-center gap-2 ml-4">
                  <button class="px-3 py-1.5 bg-secondary text-secondary-foreground rounded hover:bg-accent text-sm">详情</button>
                  <button @click="toggleSourcePause(source)" class="px-3 py-1.5 bg-secondary text-secondary-foreground rounded hover:bg-accent text-sm">{{ source.isRunning ? "暂停" : "恢复" }}</button>
                  <span v-if="isInAllChannel" class="px-3 py-1.5 bg-secondary text-secondary-foreground rounded text-sm">{{ currentChannelOf(source) }}</span>
                  <span v-else class="px-3 py-1.5 bg-muted text-muted-foreground rounded text-sm">当前频道: {{ currentChannel?.name }}</span>
                  <button @click="handleSourceRemove(source)" class="px-3 py-1.5 bg-destructive/10 text-destructive rounded hover:bg-destructive/20 text-sm">从此位置移除</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <SpaceEditDialog :open="spaceEditDialog.open" :space="spaceEditDialog.space" @close="spaceEditDialog.open = false" @save="handleSpaceSave" />
    <ChannelEditDialog :open="channelEditDialog.open" :channel="channelEditDialog.channel" @close="channelEditDialog.open = false" @save="handleChannelSave" />
    <DeleteConfirmDialog :open="deleteDialog.open" :data="deleteDialog.data" @close="deleteDialog.open = false" @confirm="handleDeleteConfirm" />
    <AddSourceDrawer :open="addSourceDrawer" :space-name="currentSpace?.name || ''" :channel-name="currentChannel?.name || ''" @close="addSourceDrawer = false" @add-source="addSourceDrawer = false" />
  </div>
</template>
